### ISSUE TITLE
Is this Workbench py3/qt5 compatible ?

### ISSUE THREAD

**Issue by luzpaz** [limikael/freecad-slic3r-tools#1]
What versions of FC does this WB support? FC has been migrating to py3/qt5, does this workbench support py3/qt5 as well ? Does it also support py2/qt4? 

BTW, nice job

**Comment by luzpaz** [comment]
Also are there any 3rd party dependencies needed?  
What is the minimum version of slic3r?  
Minimum version of FC?  
Any known issue?

**Comment by limikael** [comment]
It is py3/qt5 compatible. However, I don't think it is py2/qt4, mainly because of laziness on my part. I will do some more testing and provide documentation of the results.

**Comment by luzpaz** [comment]
I'm not saying you should make it py2/qt4 compatible. Was just wondering.

**Comment by limikael** [comment]
Ah ok... I also asked here:

https://forum.freecadweb.org/viewtopic.php?f=10&t=36398

And it seems like a general consensus that it is ok to make it Py3 only, as long as it is documented. Will do that!

**Comment by limikael** [comment]
Updated the docs
