### ISSUE TITLE
Submitting this Workbench to the Addon Manager

### ISSUE THREAD

**Issue by luzpaz** [limikael/freecad-slic3r-tools#2]
If you like you can submit this WB to be included in the Addon-Manager as an external workbench: https://github.com/FreeCAD/FreeCAD-addons

**Comment by limikael** [comment]
Would love to do that!

Will work a bit on the things you mentioned in this issue:

https://github.com/limikael/freecad-slic3r-tools/issues/1

Once resolved I will submit it.

**Comment by limikael** [comment]
Pull request created!

https://github.com/FreeCAD/FreeCAD-addons/pull/127

**Comment by limikael** [comment]
Made a mistake and submitted a new pull request, here is the new one:

https://github.com/FreeCAD/FreeCAD-addons/pull/128
