### ISSUE TITLE
Mention a dedicated thread on the FreeCAD forum for people to give you feedback about this workbench

### ISSUE THREAD

**Issue by luzpaz** [limikael/freecad-slic3r-tools#5]
Make it separate from announcement thread that you created. Then you can cross-link the URL to said thread in the README.md

**Comment by limikael** [comment]
Good idea! Where should I make this thread you think? Can you point me to a similar thread for another workbench so I can see the format for the thread?

**Comment by luzpaz** [comment]
Examples: 
* https://github.com/shaise/FreeCAD_FastenersWB/tree/master#feedback  
* https://github.com/triplus/Glass/tree/master#discussion  
* https://github.com/amrit3701/FreeCAD-Reinforcement/tree/master#extras

**Comment by luzpaz** [comment]
Nice. Not sure what commit you added this in but I'll close this ticket nevertheless

**Comment by limikael** [comment]
Oh... I haven't actually made the thread yet...

**Comment by limikael** [comment]
Ah I see... I did make a link to my old thread at the same time as I asked about the examples for the formats... Will create a new thread and change the link.

**Comment by limikael** [comment]
On 2nd thought... I think I'll use the thread that is already there, since it already has some discussions in it... so closing again... :)
